#!/bin/sh
# .husky/pre-push
. "$(dirname -- "$0")/_/husky.sh"

set -e  # stop on first failure

echo "🔍 Running code checks (formatting, linting, types)..."
pnpm check

echo "🧪 Running tests..."
pnpm test
